server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: { client-id }
            client-secret: { client-secret }
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            authorization-grant-type: authorization_code
            scope: email

          kakao:
            authorization-grant-type: authorization_code
            client-id: ${KAKAO_LOGIN_RESTAPI_KEY}
            client-secret: ${KAKAO_LOGIN_CLIENT_SECRET}
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-authentication-method: client_secret_post
            client-name: Kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/letter4u?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access:
    expiration: 1800000 # 30 mins (180000L secs)
    header: Authorization-access
  refresh:
    expiration: 604800000 # 1 weeks
    header: Authorization-refresh
